---
- name: Abort the playbook if the OS is not supported
  fail:
    msg: This OS distribution + release is not supported
  when: (ansible_os_family != 'RedHat' or ansible_distribution_major_version != '6') and (ansible_os_family != 'Debian' or ansible_distribution_major_version != '7' )

- name: Download prometheus node exporter binary
  get_url:
    url: "{{ node_exporter_from_url }}"
    checksum: "{{ node_exporter_checksum }}"
    dest: /opt

- name: Unpack node_exporter
  unarchive:
    src: /opt/{{ node_exporter_package_filename }}
    dest: /opt
    remote_src: true
  # should end up as /opt/node_exporter-$VERSION.linux-amd64/


- name: Create a simply-named dir symlink to current version
  file:
    state: link
    src: /opt/node_exporter-{{ node_exporter_version }}.linux-amd64
    dest: /opt/prometheus


- name: Create node_exporter group
  group:
    name: "{{ node_exporter_groupname }}"
    state: present
    system: true

- name: Create node_exporter user
  user:
    name: "{{ node_exporter_username }}"
    group: "{{ node_exporter_groupname }}"
    state: present
    system: true
    shell: /sbin/nologin

- name: Precipitate log file
  copy:
    content: ''
    force: false
    dest: "{{ node_exporter_log_file }}"
    mode: '0640'
    owner: "{{ node_exporter_username }}"
    group: adm

- name: Configure logrotate
  template:
    src: templates/logrotate.j2
    dest: /etc/logrotate.d/prometheus
    backup: false

- name: Configure init.d script
  when: ansible_os_family == 'RedHat'
  template:
    src: templates/redhat-init.d.j2
    dest: /etc/init.d/{{ node_exporter_service_name }}
    backup: false
    mode: '0755'

- name: Configure init.d script
  when: ansible_os_family == 'Debian'
  template:
    src: templates/debian-init.d.j2
    dest: /etc/init.d/{{ node_exporter_service_name }}
    backup: false
    mode: '0755'

- name: add args to service file
  when: ansible_os_family == 'Debian'
  template:
    src: templates/debian-defaults.j2
    dest: /etc/default/{{ node_exporter_service_name }}
    backup: false
    mode: '0755'

- name: Make sure service is running and enabled at boot
  service:
    name: "{{ node_exporter_service_name }}"
    state: started
    enabled: true
